/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "EClustPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "EClustVpc": {
      "type": "sst.aws.Vpc"
    }
    "ExecuteFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Runner": {
      "service": string
      "type": "sst.aws.Service"
    }
    "ShardConfig": {
      "SHARD_MANAGER_HOST": string
      "SHARD_MANAGER_PORT": number
      "type": "sst.sst.Linkable"
    }
    "ShardManager": {
      "service": string
      "type": "sst.aws.Service"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}